name: Release

on:
  push:
    branches:
      - 'master'
      - 'release/*'
  pull_request:
    branches:
      - 'master'

jobs:

  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Detekt
        run: ./gradlew detekt
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Detekt
          path: build/reports/detekt/detekt.html

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Test
        run: ./gradlew test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Unit Test
          path: "build/reports/tests/"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble
        run: ./gradlew assemble
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Assemble
          path: build/libs
